version: '2.3'

services:
  postgres:
    container_name: postgres-busy-flights
    image: travix/postgres
    ports:
      - "127.0.0.1:15633:5432"
    environment:
      PGUSER: postgres
      POSTGRES_DB: busy-flights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres